name: Deploy Design-Studio to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@500ac625ca2dd40cbd15f7659af953801858032a
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEWS_92 }}"
          projectId: "news-92"
          channelId: "live"
          entryPoint: "."
          firebaseToolsVersion: "15.29.0"
          disableComment: true
